### ISSUE TITLE
API request fails with API key error

### ISSUE THREAD

**Issue by busybox11** [pmcdonough8133/WeeklyChartsSourceCode#1]
Hey,
I'm trying to use this project to generate a video.
I have an error:

```
Traceback (most recent call last):
  File "/home/busybox/host/WeeklyChartsSourceCode/main.py", line 189, in <module>
    main()
  File "/home/busybox/host/WeeklyChartsSourceCode/main.py", line 33, in main
    for x in getweeklychartlistRAW['weeklychartlist']['chart'] :
KeyError: 'weeklychartlist'
```

By printing the `getweeklychartlistRAW` object, I have the following result:
```JSON
{'message': 'Invalid API key - You must be granted a valid key by last.fm', 'error': 10}
```

Is this a known behavior?

**Comment by pmcdonough8133** [comment]
Are you running the script from the source code or the .exe file from here: https://github.com/pmcdonough8133/WeeklyCharts

**Comment by busybox11** [comment]
I'm on Linux, I'm running the Python script manually.
I just saw the variable `apiKey` which is using a default value, I'm going to change this now, and it will probably work haha.
I'm going to keep you updated, thanks!

**Comment by pmcdonough8133** [comment]
Feel free to create your own here: https://www.last.fm/api/account/create

**Comment by busybox11** [comment]
Yup, actually I used an old key I had but it works too haha.
I also had to strip "\n" from the `dateFormat` variable and now it is getting pictures and working on weeks.
Apparently it's fine.
Thank you!

**Comment by pmcdonough8133** [comment]
That's good QoL improvement I didn't catch before, added it to the main code along a few other error handling improvements

**Comment by busybox11** [comment]
Great!
I'm glad to help haha
